# Generated by Django 3.1.7 on 2021-03-29 05:10

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='Country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
